# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20181017_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
