# Generated by Django 2.2 on 2020-07-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0010_auto_20200422_1731'),
        ('ratings', '0013_auto_20200422_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingparameter',
            options={'verbose_name': 'rating parameter', 'verbose_name_plural': 'rating parameters'},
        ),
        migrations.AlterField(
            model_name='ratingparameter',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='ratingparameter',
            unique_together={('slug', 'channel')},
        ),
    ]
