# Generated by Django 2.2 on 2020-07-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0015_ratingrequest_permission_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingparameter',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Required'),
        ),
    ]
