# Generated by Django 2.2 on 2020-09-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0006_digesttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='digesttext',
            name='default_content',
            field=models.TextField(blank=True, null=True, verbose_name='Default context'),
        ),
    ]
