# Generated by Django 2.2 on 2020-09-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0007_digesttext_default_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='digesttext',
            name='keep_text',
            field=models.BooleanField(default=False, verbose_name='Manter conteúdo após envio'),
        ),
        migrations.AlterField(
            model_name='digesttext',
            name='text_content',
            field=models.TextField(blank=True, null=True, verbose_name='Conteúdo'),
        ),
    ]
