# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_remove_user_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_completed',
            field=models.BooleanField(default=False, verbose_name='User profile completed'),
        ),
    ]
