# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_uploads', '0006_auto_20170613_1424'),
        ('ovp_testimonials', '0008_auto_20170613_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ovp_uploads.UploadedImage', verbose_name='image'),
        ),
    ]
