# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-22 17:21
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_auto_20191128_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Metadata'),
        ),
    ]
