# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 13:42
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField(default='', max_length=3000, verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'faq',
                'verbose_name_plural': 'faq',
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqcategory_channel', to='channels.Channel')),
            ],
            options={
                'verbose_name': 'faq category',
                'verbose_name_plural': 'faq categories',
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='faq.FaqCategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='faq',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_channel', to='channels.Channel'),
        ),
    ]
