version: 2.1

executors:
  build-test-and-release:
    docker:
      - image: circleci/python:3.7
        environment:
          DATABASE_URL: postgres://root:@localhost:5432/circle-test

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test

    working_directory: ~/repo

jobs:
  build:
    executor: build-test-and-release
    steps:
      - checkout

      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "requirements/requirements-dev.txt" }}-{{ checksum "requirements/requirements-project.txt" }}
      #       - v1-dependencies-

      - run:
          name: Install dependencies
          # Arquivo para importar os demais requirements
          command: pip install -r requirements/requirements-global.txt --user

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: - v1-dependencies-{{ checksum "requirements/requirements-dev.txt" }}-{{ checksum "requirements/requirements-project.txt" }}

      - run:
          name: Run tests with Postgres
          command: python test/runtests.py

      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  build-test-and-release:
    jobs:
      - build
