version: 2.1

executors:
  build-test-and-release:
    docker:
      - image: circleci/python:3.7
        environment:
          DATABASE_URL: postgres://root:@localhost:5432/circle-test

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test

    working_directory: ~/repo

jobs:
  build:
    executor: build-test-and-release
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements/requirements-global.txt --user
      
      # Executando testes por Apps
      - run:
          name: Run tests catalogue with Postgres
          command: python test/runtests.py ovp.apps.catalogue

      - run:
          name: Run tests channels with Postgres
          command: python test/runtests.py ovp.apps.channels

      - run:
          name: Run tests core with Postgres
          command: python test/runtests.py ovp.apps.core

      - run:
          name: Run tests faq with Postgres
          command: python test/runtests.py ovp.apps.faq

      - run:
          name: Run tests gallery with Postgres
          command: python test/runtests.py ovp.apps.gallery

      - run:
          name: Run tests organizations with Postgres
          command: python test/runtests.py ovp.apps.organizations

      - run:
          name: Run tests projects with Postgres
          command: python test/runtests.py ovp.apps.projects

      - run:
          name: Run tests ratings with Postgres
          command: python test/runtests.py ovp.apps.ratings
  
      - run:
          name: Run tests search with Postgres
          command: python test/runtests.py ovp.apps.search

      - run:
          name: Run tests uploads with Postgres
          command: python test/runtests.py ovp.apps.uploads
    
      - run:
          name: Run tests users with Postgres
          command: python test/runtests.py ovp.apps.users

      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  build-test-and-release:
    jobs:
      - build
