# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-28 19:03
from __future__ import unicode_literals

from django.db import migrations

def foward_func(apps, schema_editor):
    Channel = apps.get_model("channels", "Channel")
    channel = Channel(name="default")
    channel.save()
    return True

def rewind_func(apps, schema_editor):
    Channel = apps.get_model("channels", "Channel")
    Channel.objects.all().delete()
    return True


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel'),
    ]

    operations = [
        migrations.RunPython(foward_func, rewind_func)
    ]
