# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'catalogue',
                'verbose_name_plural': 'catalogues',
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DateDeltaFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=0, verbose_name='Days')),
                ('weeks', models.IntegerField(default=0, verbose_name='Weeks')),
                ('months', models.IntegerField(default=0, verbose_name='Months')),
                ('years', models.IntegerField(default=0, verbose_name='Years')),
                ('operator', models.CharField(choices=[('exact', 'Exact'), ('gt', 'Greater than'), ('gte', 'Greater than or equal to'), ('lt', 'Lesser than'), ('lte', 'Lesser than or equal to')], default='exact', max_length=30, verbose_name='Operator')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datedeltafilter_channel', to='channels.Channel')),
            ],
            options={
                'abstract': False,
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('amount', models.IntegerField(default=20, verbose_name='Amount')),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='catalogue.Catalogue')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_channel', to='channels.Channel')),
            ],
            options={
                'verbose_name': 'section',
                'verbose_name_plural': 'sections',
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SectionFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CATEGORY', 'Category'), ('DATEDELTA', 'Date delta')], max_length=30, verbose_name='Filter type')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectionfilter_channel', to='channels.Channel')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='catalogue.Section')),
            ],
            options={
                'verbose_name': 'section filter',
                'verbose_name_plural': 'section filters',
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
    ]
