# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('projects', '0001_initial'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryfilter',
            name='categories',
            field=models.ManyToManyField(to='projects.Category'),
        ),
        migrations.AddField(
            model_name='categoryfilter',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryfilter_channel', to='channels.Channel'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_channel', to='channels.Channel'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('slug', 'catalogue')]),
        ),
        migrations.AlterUniqueTogether(
            name='catalogue',
            unique_together=set([('slug', 'channel')]),
        ),
    ]
