# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 13:42
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('unapplied', 'Canceled'), ('confirmed-volunteer', 'Confirmed Volunteer'), ('not-volunteer', 'Not a Volunteer')], default='applied', max_length=30, verbose_name='status')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('canceled', models.BooleanField(default=False, verbose_name='canceled')),
                ('canceled_date', models.DateTimeField(blank=True, null=True, verbose_name='canceled date')),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('email', models.CharField(blank=True, max_length=190, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='phone')),
            ],
            options={
                'verbose_name': 'apply',
                'verbose_name_plural': 'applies',
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True, verbose_name='description')),
                ('highlighted', models.BooleanField(default=False, verbose_name='Highlighted')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
                ('can_be_done_remotely', models.BooleanField(default=False, verbose_name='This job can be done remotely')),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JobDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Label')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
            ],
            options={
                'verbose_name': 'job date',
                'verbose_name_plural': 'job dates',
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Project name')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('highlighted', models.BooleanField(default=False, verbose_name='Highlighted')),
                ('applied_count', models.IntegerField(default=0, verbose_name='Applied count')),
                ('max_applies', models.IntegerField(default=1)),
                ('max_applies_from_roles', models.IntegerField(default=0)),
                ('public_project', models.BooleanField(default=True, verbose_name='Public')),
                ('minimum_age', models.IntegerField(default=0, verbose_name='Minimum Age')),
                ('hidden_address', models.BooleanField(default=False, verbose_name='Hidden address')),
                ('crowdfunding', models.BooleanField(default=False, verbose_name='Crowdfunding')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Published date')),
                ('closed', models.BooleanField(default=False, verbose_name='Closed')),
                ('closed_date', models.DateTimeField(blank=True, null=True, verbose_name='Closed date')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Deleted date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
                ('details', ckeditor.fields.RichTextField(max_length=3000, verbose_name='Details')),
                ('description', models.TextField(blank=True, max_length=160, null=True, verbose_name='Short description')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectbookmark_channel', to='channels.Channel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='projects.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VolunteerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Role name')),
                ('prerequisites', models.TextField(blank=True, default=None, max_length=1024, null=True, verbose_name='Prerequisites')),
                ('details', models.TextField(blank=True, default=None, max_length=1024, null=True, verbose_name='Details')),
                ('vacancies', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Vacancies')),
                ('applied_count', models.IntegerField(default=0, verbose_name='Applied count')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteerrole_channel', to='channels.Channel')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'volunteer role',
                'verbose_name_plural': 'volunteer roles',
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Weekly hours')),
                ('description', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Description')),
                ('can_be_done_remotely', models.BooleanField(default=False, verbose_name='This job can be done remotely')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_channel', to='channels.Channel')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'work',
                'verbose_name_plural': 'works',
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
    ]
