# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20180704_1042'),
        ('channels', '0001_initial'),
        ('organizations', '0002_auto_20180704_1042'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.SimpleAddress', verbose_name='address'),
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(blank=True, to='projects.Category', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='project',
            name='causes',
            field=models.ManyToManyField(to='core.Cause', verbose_name='causes'),
        ),
        migrations.AddField(
            model_name='project',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_channel', to='channels.Channel'),
        ),
        migrations.AddField(
            model_name='project',
            name='commentaries',
            field=models.ManyToManyField(to='core.Commentary', verbose_name='commentaries'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploads.UploadedImage', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(to='core.Skill', verbose_name='skills'),
        ),
        migrations.AddField(
            model_name='jobdate',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobdate_channel', to='channels.Channel'),
        ),
        migrations.AddField(
            model_name='jobdate',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='projects.Job', verbose_name='job'),
        ),
        migrations.AddField(
            model_name='job',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_channel', to='channels.Channel'),
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='category',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_channel', to='channels.Channel'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_image', to='uploads.UploadedImage', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='apply',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_channel', to='channels.Channel'),
        ),
        migrations.AddField(
            model_name='apply',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='apply',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.VolunteerRole', verbose_name='role'),
        ),
        migrations.AddField(
            model_name='apply',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('slug', 'channel')]),
        ),
        migrations.AlterUniqueTogether(
            name='apply',
            unique_together=set([('email', 'project')]),
        ),
    ]
