# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-12 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('projects', '0062_auto_20180705_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='items',
            field=models.ManyToManyField(blank=True, to='items.Item', verbose_name='items'),
        ),
    ]
