# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-01 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_auto_20180712_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Newsletter'),
        ),
        migrations.AddField(
            model_name='project',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Newsletter'),
        ),
    ]
