# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-25 16:49
from __future__ import unicode_literals

from django.db import migrations

def forward(apps, schema_editor):
    Apply = apps.get_model('projects.Apply')
    Apply.objects.filter(status="unapplied").update(status="unapplied-by-volunteer")
    Apply.objects.filter(status="not-volunteer").update(status="unapplied-by-organization")

def backwards(apps, schema_editor):
    Apply = apps.get_model('projects.Apply')
    Apply.objects.filter(status="unapplied-by-volunteer").update(status="unapplied")
    Apply.objects.filter(status="unapplied-by-organization").update(status="not-volunteer")

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0094_auto_20191121_2004'),
    ]

    operations = [
        migrations.RunPython(forward, backwards)
    ]
