# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-26 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_remove_channel_subchannels'),
        ('projects', '0095_auto_20191125_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, verbose_name='status')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Status date')),
            ],
            options={
                'abstract': False,
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='apply',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('unapplied-by-volunteer', 'Canceled by volunteer'), ('unapplied-by-organization', 'Canceled by organization'), ('confirmed-volunteer', 'Confirmed Volunteer')], default='applied', max_length=30, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='applystatushistory',
            name='apply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Apply'),
        ),
        migrations.AddField(
            model_name='applystatushistory',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applystatushistory_channel', to='channels.Channel'),
        ),
    ]
