# Generated by Django 2.2 on 2020-09-14 23:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0097_project_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
