# Generated by Django 2.2 on 2020-09-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0098_project_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='not_published_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Duplicated'), (1, 'Unfit'), (2, 'No response from organization'), (3, 'Other')], null=True, verbose_name="Reason it's not published"),
        ),
    ]
