# Generated by Django 2.2 on 2020-09-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0099_project_not_published_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='not_published_reason',
        ),
    ]
