# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-13 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_testimonials', '0007_auto_20170504_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(max_length=3000, verbose_name='Contents'),
        ),
    ]
