# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-22 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_testimonials', '0009_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='video',
            field=models.CharField(default='', max_length=150, verbose_name='Video'),
        ),
    ]
