# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 17:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovp_testimonials', '0010_testimonial_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Testimonial date'),
        ),
    ]
