# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import ovp.apps.channels.models.mixins
import ovp.apps.uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ovp.apps.uploads.models.ImageName(), verbose_name='Image 350x260')),
                ('image_small', django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=False, null=True, quality=60, size=[350, 260], upload_to=ovp.apps.uploads.models.ImageName('-small'))),
                ('image_medium', django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=False, null=True, quality=60, size=[420, 312], upload_to=ovp.apps.uploads.models.ImageName('-medium'))),
                ('image_large', django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=False, null=True, quality=60, size=[1260, 936], upload_to=ovp.apps.uploads.models.ImageName('-large'))),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(blank=True, default=None, max_length=36, verbose_name='UUID')),
                ('category', models.CharField(blank=True, choices=[('organization', 'Organization'), ('project', 'Project')], default=None, max_length=24, null=True, verbose_name='Category')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Name')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadedimage_channel', to='channels.Channel')),
            ],
            options={
                'verbose_name': 'uploaded image',
                'verbose_name_plural': 'uploaded images',
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
    ]
