# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('channels', '0001_initial'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='channelcontact',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channelcontact_channel', to='channels.Channel'),
        ),
        migrations.AddField(
            model_name='cause',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause_channel', to='channels.Channel'),
        ),
        migrations.AddField(
            model_name='cause',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploads.UploadedImage', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='availability',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_channel', to='channels.Channel'),
        ),
        migrations.AddField(
            model_name='addresscomponenttype',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresscomponenttype_channel', to='channels.Channel'),
        ),
        migrations.AddField(
            model_name='addresscomponent',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresscomponent_channel', to='channels.Channel'),
        ),
        migrations.AddField(
            model_name='addresscomponent',
            name='types',
            field=models.ManyToManyField(to='core.AddressComponentType'),
        ),
    ]
