# Generated by Django 2.2 on 2020-08-05 17:59

from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0010_auto_20200422_1731'),
        ('core', '0042_auto_20200422_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pixel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, verbose_name='source')),
                ('meta', models.CharField(blank=True, max_length=100, null=True, verbose_name='meta')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pixel_channel', to='channels.Channel')),
            ],
            options={
                'verbose_name': 'pixel',
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
    ]
