# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 13:42
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import ovp.apps.channels.models.mixins
import ovp.apps.organizations.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('website', models.URLField(blank=True, default=None, null=True, verbose_name='Website')),
                ('facebook_page', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Facebook')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Organization'), (1, 'School'), (2, 'Company'), (3, 'Group of volunteers')], default=0, verbose_name='Type')),
                ('details', ckeditor.fields.RichTextField(blank=True, default=None, max_length=3000, null=True, verbose_name='Details')),
                ('description', models.CharField(blank=True, max_length=320, null=True, verbose_name='Short description')),
                ('hidden_address', models.BooleanField(default=False, verbose_name='Hidden address')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('document', models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[ovp.apps.organizations.validators.validate_CNPJ], verbose_name='CNPJ')),
                ('contact_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsible name')),
                ('contact_email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Responsible email')),
                ('contact_phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsible phone')),
                ('highlighted', models.BooleanField(default=False, verbose_name='Highlighted')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Published date')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Deleted date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified date')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationinvite_channel', to='channels.Channel')),
            ],
            options={
                'verbose_name': 'organization_invite',
            },
            bases=(ovp.apps.channels.models.mixins.ChannelCreatorMixin, models.Model),
        ),
    ]
