# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20181017_1810'),
        ('organizations', '0044_auto_20180921_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='rating',
            field=models.FloatField(default=None, null=True, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='organization',
            name='ratings',
            field=models.ManyToManyField(to='ratings.Rating'),
        ),
    ]
