# Generated by Django 2.2 on 2020-06-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0061_auto_20200422_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='not_published_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Organization'), (1, 'School'), (2, 'Company'), (3, 'Group of volunteers')], null=True, verbose_name="Reason it's not published"),
        ),
        migrations.AddField(
            model_name='organization',
            name='salesforce_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Salesforce ID'),
        ),
    ]
