# Generated by Django 2.2 on 2020-07-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0062_auto_20200623_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='not_published_reason',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Duplicated'), (1, 'Unfit'), (2, 'No response from organization'), (3, 'Other')], null=True, verbose_name="Reason it's not published"),
        ),
    ]
